name: Packer Virtualbox
on:
  - push

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: 1.5.6

      - name: Build image from template
        run: packer build -only virtualbox-iso ubuntu-focal-amd64.json
        env:
            VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
